name: show_time
description: Track your favorite shows & episodes with ease.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.4+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ! UI elements / widgets
  carousel_slider: ^4.1.1
  sliding_up_panel: ^2.0.0+1
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  fluttertoast: ^8.0.6
  font_awesome_flutter: ^9.0.0
  percent_indicator: ^4.0.1
  fade_shimmer: ^2.0.1
  shimmer: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  fl_chart: ^0.36.3
  timeline_tile: ^2.0.0
  roundcheckbox: ^2.0.5
  hovering: ^1.0.4
  syncfusion_flutter_sliders: ^20.2.46
  syncfusion_flutter_gauges: ^20.2.46

  # ! Firebase & Stuff
  firebase_core: "1.12.0"
  firebase_core_platform_interface: "4.2.4"
  cloud_firestore: "3.1.9"
  cloud_firestore_web: ^2.6.5
  firebase_auth: "3.3.8"

  # ! Services
  connectivity: ^3.0.3
  html: ^0.15.0
  email_validator: ^2.0.1
  flutter_secure_storage: ^4.2.0
  intl: ^0.17.0
  local_auth: ^1.1.5
  floor: ^1.3.0
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3
  bloc: ^7.2.0
  get_it: ^7.2.0
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+3

  # ! Animations
  animations: ^2.0.1
  simple_animations: ^3.1.1
  flutter_staggered_animations: ^1.0.0
  flutter_animated_dialog: ^2.0.0
  animated_size_and_fade: ^2.0.0
  flare_flutter: ^3.0.0

  # ! Google packages
  google_fonts: ^2.0.0
  google_nav_bar: ^5.0.4
  google_sign_in: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.3.0
  build_runner: ^2.1.2
  dependency_validator: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - showTIME.png
    - showTIMEsmall.png
    - no internet.flr
    - notfound.flr
    - waiting.flr
    - blink.flr
    - empty.flr
    - empty-blue.flr
    - ohno.flr
    - loadingcouch.flr
    - loadingcouch-white.flr
    - flowingbg.flr
    - showtime-avatar.png
    - google_logo.png
    - fingerprint.flr
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Light.ttf
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-Black.ttf
          weight: 900
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway-ExtraBold.ttf
          weight: 800

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
