name: show_time
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI elements / widgets
  carousel_slider: ^4.0.0-nullsafety.0
#  sliding_up_panel: ^1.0.2  # not yet null safety  :(
  sliding_sheet: ^0.5.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  fluttertoast: ^8.0.3
  font_awesome_flutter: ^9.0.0
  percent_indicator: ^3.3.0-nullsafety.1
#  status_alert: ^0.1.3
  autocomplete_textfield: ^1.7.3
  chips_choice: ^2.0.1
  flip_panel: ^1.0.1
  expandable: ^5.0.1
  shimmer: ^2.0.0-nullsafety.0
  circular_check_box: ^1.0.4
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  slide_countdown_clock: ^1.0.3
  fl_chart: ^0.20.1
  timeline_tile: ^2.0.0
  roundcheckbox: ^2.0.0-nullsafety.0
  hovering: ^1.0.4
  material_floating_search_bar: ^0.3.3
  multi_select_flutter: ^4.0.0
  syncfusion_flutter_sliders: ^19.1.54-beta
  syncfusion_flutter_gauges: ^19.1.54+1
  # UI elements / widgets

  # Firebase & Stuff
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  cloud_firestore_web: ^1.0.3
  firebase_auth: ^1.0.1
  # Firebase & Stuff

  # Services
  connectivity: ^3.0.3
  html: ^0.15.0
  email_validator: ^2.0.1
  flutter_secure_storage: ^4.1.0
  intl: ^0.17.0
  local_auth: ^1.1.0
  floor: ^1.0.0
#
  provider: ^5.0.0
  get: ^4.1.3
  # Services

  # Animations
  animations: ^2.0.0
  simple_animations: ^3.0.3
  flutter_staggered_animations: ^1.0.0
  flutter_animated_dialog: ^2.0.0
  animated_size_and_fade: ^2.0.0
  animate_icons: ^2.0.0
  auto_animated: ^3.0.0
  flare_flutter: ^3.0.0
  # Animations

  # Google packages
  google_fonts: ^2.0.0
  google_nav_bar: ^5.0.3
  google_sign_in: ^5.0.1






dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.0.0
  build_runner: ^1.11.5


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - showTIME.png
     - showTIMEsmall.png
     - no internet.flr
     - notfound.flr
     - waiting.flr
     - blink.flr
     - empty.flr
     - empty-blue.flr
     - ohno.flr
     - loadingcouch.flr
     - loadingcouch-white.flr
     - flowingbg.flr
     - showtime-avatar.png
     - google_logo.png
     - fingerprint.flr
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Raleway
     fonts:
       - asset: fonts/Raleway-Light.ttf
       - asset: fonts/Raleway-Bold.ttf
         weight: 700
       - asset: fonts/Raleway-Black.ttf
         weight: 900
       - asset: fonts/Raleway-Regular.ttf
       - asset: fonts/Raleway-Thin.ttf
         weight: 100
       - asset: fonts/Raleway-ExtraBold.ttf
         weight: 800

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
