name: eWoke
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  carousel_slider: ^3.0.0
  percent_indicator: ^2.1.9+1
  sliding_up_panel: ^1.0.2
  animations: ^1.1.2
  flip_card: ^0.4.4
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  status_alert: ^0.1.3
  grouped_list: ^3.7.1
  font_awesome_flutter: ^8.11.0
  autocomplete_textfield: ^1.7.3
  chips_choice: ^2.0.1
  connectivity: ^2.0.2
  fluttertoast: ^7.1.6
  flutter_multi_carousel: ^1.0.3
  palette_generator: ^0.2.3
  html: ^0.14.0+4
  simple_animations: ^2.5.0
  expandable: ^4.1.4
  flutter_staggered_animations: ^0.1.2
  animate_icons: ^1.0.0
  carousel_pro: ^1.0.0
  flip_panel: ^1.0.1
  auto_search: ^1.0.6
  shimmer: ^1.1.2
  flutter_login: ^1.0.14
  firebase_auth: ^0.20.0+1
  flutter_animated_dialog: ^1.2.0
  circular_check_box: ^1.0.4
  animated_size_and_fade: ^1.1.4
  email_validator: ^1.0.6
  flutter_secure_storage: ^3.3.5
  auto_size_text: ^2.1.0
  auto_animated: ^2.1.0
  cached_network_image: ^2.5.0
  flutter_staggered_grid_view: ^0.3.4
  slide_countdown_clock: ^1.0.3
  google_fonts: ^1.1.2
  snapping_sheet: ^2.0.2
#  sticky_grouped_list: ^1.2.0
  sticky_and_expandable_list: ^0.2.3
  google_nav_bar: ^3.2.0
  progress_state_button: ^1.0.2
  tab_indicator_styler: ^1.0.0
  fl_chart: ^0.12.2
  intl: ^0.16.1
  provider: ^4.3.3
  local_auth: ^0.6.3+4
  sqflite: ^1.3.2+3
  floor: ^0.18.0
  google_sign_in: ^4.5.9
  adaptive_dialog: ^0.9.3
  blurrycontainer: ^0.0.1
  timelines: ^0.0.2+1
  get: ^3.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.18.0
  build_runner: ^1.11.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - showTIME.png
     - showTIMEsmall.png
     - no internet.flr
     - notfound.flr
     - waiting.flr
     - blink.flr
     - empty.flr
     - empty-blue.flr
     - ohno.flr
     - loadingcouch.flr
     - loadingcouch-white.flr
     - flowingbg.flr
     - showtime-avatar.png
     - google_logo.png
     - fingerprint.flr
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Raleway
     fonts:
       - asset: fonts/Raleway-Light.ttf
       - asset: fonts/Raleway-Bold.ttf
         weight: 700
       - asset: fonts/Raleway-Black.ttf
         weight: 900
       - asset: fonts/Raleway-Regular.ttf
       - asset: fonts/Raleway-Thin.ttf
         weight: 100
       - asset: fonts/Raleway-ExtraBold.ttf
         weight: 800

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
