// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBOmr8kizHaszbfnlpBvqspPofo4K4BJw',
    appId: '1:897799355695:web:5ceab3c2086fb84801b5da',
    messagingSenderId: '897799355695',
    projectId: 'memento-388f3',
    authDomain: 'memento-388f3.firebaseapp.com',
    databaseURL: 'https://memento-388f3.firebaseio.com',
    storageBucket: 'memento-388f3.appspot.com',
    measurementId: 'G-G4Q5ERVBMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV0sMnasf79Hs2VUfaB16S2_vub2b-jwo',
    appId: '1:897799355695:android:6f1677fd1b42a2b901b5da',
    messagingSenderId: '897799355695',
    projectId: 'memento-388f3',
    databaseURL: 'https://memento-388f3.firebaseio.com',
    storageBucket: 'memento-388f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgc8jKfcZ1aEcYYiuaMv4eZ0kcYZBLGJI',
    appId: '1:897799355695:ios:ffaf247811b70a5d01b5da',
    messagingSenderId: '897799355695',
    projectId: 'memento-388f3',
    databaseURL: 'https://memento-388f3.firebaseio.com',
    storageBucket: 'memento-388f3.appspot.com',
    iosClientId: '897799355695-gcpjvqgn3hkmj8diiofo2pn8f8b7e3v7.apps.googleusercontent.com',
    iosBundleId: 'ro.appforte.showtimeFlutter',
  );
}
